
name: Deploy
on: [push, workflow_dispatch]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Build project
        run: npm i && npm run build

      - name: Clean up
        run: rm -rf node_modules && rm package-lock.json

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: pocket
          entrypoint: ./deploy/index.js
